[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.chal1jer]
    address=":80"
[providers.file]
  directory = "/home/etud/Documents/xavki/traefik/services/"
  watch = true

