[accesslog]
[api]
  #insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.chal1jer]
    address=":80"
  [entryPoints.api]
    address=":8080"
[providers.file]
  directory = "/home/etud/Documents/xavki/traefik/1.load_balancer/services/"
  watch = true

