[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.chal1jer]
    address=":80"
   [entryPoints.chal1jer.http.redirections]
      [entryPoints.chal1jer.http.redirections.entryPoint]
        to = "chal1jer_secure"
        scheme = "https" 
  [entryPoints.chal1jer_secure]
    address=":443"

[providers.file]
  directory = "/home/etud/Documents/traefik/2.certificat_auto_signe/services/"
  watch = true

